[build]
  publish = "dist" # Ensure this is the correct output directory for your build
  command = "npm run build" # This command should exist in your package.json

[[redirects]]
  from = "/api/*"
  to = "http://43.205.212.94:8080/:splat" # Proxy requests to your API
  status = 200
  force = true
